### ISSUE TITLE
remembered pattern includes season and episode number

### ISSUE THREAD

**Issue by daed-alus** [MediaBrowser/Emby.AutoOrganize#11]
![unbenannt](https://user-images.githubusercontent.com/16777083/39141951-87690bb8-4729-11e8-9909-b308264a269b.PNG)
the filename for the 2nd pattern was from this form 'st-e-s02e01-[resolution].[ext]'

server v3.3.1.23
plugin v1.2.3.0

**Comment by PoppyPop** [comment]
i think this is related to #6.
The only way i have reproduce this error, is forcing the return of the Emby.Naming name parser.
But with your server version, this should not happen.
Maybe i fixed it in the PR #10.

Can you give me the extension ? i saw some code that change the behavior of the parser un function of the extension.

**Comment by daed-alus** [comment]
the extension is .mkv
just to add, still happens with .24

**Comment by PoppyPop** [comment]
I am still not able to reproduce ... 
I test the thing with 2 setups : Windows and Docker linux (The same version Version 3.3.1.24 beta)
Stock 1.2.3.0 plugin (Windows is a fresh install, Docker the "production" install)

Each time i get a good identification.

like #6, You can check the server log in debug for a line like Extracted information from `D:\....\blood-drive-s01e11-1080p.mkv. Series name blood-drive, Season 1, Episode 11` ?

Do you have a long path ? Could you send me an entire server log in debug mode ?
I really think all your problem are the same thing, but i don't understand the why for the moment

**Comment by daed-alus** [comment]
server v3.3.1.24
plugin v1.2.3.0

season and episode number get extracted correctly by the server, if not already remembered patterns, that get sorted correctly, i think also wouldn't work
```
2018-04-25 23:30:32.241 Info App: Sorting file D:\...\steins-gate-s01e01-1080p.mkv
2018-04-25 23:30:32.303 Debug App: Extracted information from D:\...\steins-gate-s01e01-1080p.mkv. Series name steins-gate, Season 1, Episode 1
2018-04-25 23:30:32.361 Warn App: Unable to find series in library matching name steins-gate
```
![unbenannt2](https://user-images.githubusercontent.com/16777083/39274497-7163b9c0-48e2-11e8-8741-69e0296d5544.PNG)

and then when clicking the + to add a new series i get this
![unbenannt3](https://user-images.githubusercontent.com/16777083/39275040-23c57bca-48e4-11e8-895a-16d048ef9ca0.PNG)

**Comment by PoppyPop** [comment]
In your data folder, can you send me the file `fileorganization.db` ?
Be careful to have an serie/episode in the same case.
This file is the database it store the extractedName, season and episode.
I Warn, this file contains the full path to the Media file.

If you don't want to send the file, you could check yourself with a tool like `SQLiteDatabaseBrowserPortable`

Close your Server OR copy the database file

Clic the "Open DataBase"
![image](https://user-images.githubusercontent.com/8221539/39316286-0edf79a0-4979-11e8-9d4e-7585ee7b3fde.png)
Select the `fileorganization.db` file

Clic "Browse Data"
![image](https://user-images.githubusercontent.com/8221539/39316354-3e494f40-4979-11e8-9fd8-0b2675ce0220.png)

Check the extracted Value
![image](https://user-images.githubusercontent.com/8221539/39316432-71c1b61e-4979-11e8-929d-1bf3d7158cbd.png)

**Comment by daed-alus** [comment]
ok with server v3.3.1.25 it works again

manual organize dialog now default to 'series' but is empty, so i think #6 is back?
![unbenannt](https://user-images.githubusercontent.com/16777083/39317905-091ee4c0-497d-11e8-8196-d397694dff67.PNG)

only switching to 'blank/movie' and back to 'series' fills the forms correctly 
![unbenannt2](https://user-images.githubusercontent.com/16777083/39317908-0956bc2e-497d-11e8-9054-248364dff586.PNG)

and further the series name gets filled and later remembered correctly
![unbenannt3](https://user-images.githubusercontent.com/16777083/39317909-0990a90c-497d-11e8-8465-11ca1becae2a.PNG)

![unbenannt4](https://user-images.githubusercontent.com/16777083/39317911-0a120236-497d-11e8-8088-f7c7b2cad834.PNG)
![unbenannt5](https://user-images.githubusercontent.com/16777083/39318395-4ce57af6-497e-11e8-8d94-92f5e380e4e0.PNG)

**Comment by daed-alus** [comment]
server v3.4.0.0 & v3.4.0.1 beta brought back the initial issue,
episodes get recognizes as mediatype 'movie' again and so season/episode# gets again included in the pattern

**Comment by PoppyPop** [comment]
Did you use the same watch folder for movies and TV shows ? If yes, the actual published version have only partial support.

You could try to use the automated build of my local repos. 
You just have to replace the autoorganize full in the plug-in folder.

I just warn you that, new smartmatches will not appear if you rollback to the standard version.

https://github.com/PoppyPop/Emby.AutoOrganize/releases/tag/5.0.0.2

I'm still waiting for @luke to review the PR #10, but I think it will resolve some of your issue.

**Comment by daed-alus** [comment]
yes, was a combined folder, couldn't imagine that your "detection" is only based on the watchfolder

i've split it up now and it seems to work as expected resolving this and #6 

if a combined watched folder is not/"only partial" supported and you know, it why is there no hint/note about it?

**Comment by PoppyPop** [comment]
Simply, because I never tested it.

I noticed it, before my holiday, and made a fix to handle it.

When I tried to reproduce your problem, i came across strange thing in this configuration, but not the same problems as yours.

The PR #10 resolve this issue. I will add a comment to reference this issue.
