### ISSUE TITLE
Movie Name pattern %mn includes Year

### ISSUE THREAD

**Issue by daed-alus** [MediaBrowser/Emby.AutoOrganize#3]
the pattern `%mn` is in the form `Movie Name (Year)`

`%mn` should be reduced to movie name only and for the year a new pattern should be created

**Comment by PoppyPop** [comment]
Can you give me the exact filename ? 
I think it's related to a wrong file name detection, i used the official way to detect it specified in this [document](https://github.com/MediaBrowser/Wiki/wiki/Movie%20naming)

**Comment by daed-alus** [comment]
the exact resulted filename after sorting is, as stated above, `%mn.ext` -> `Movie Name (Year).ext`
i also had some "official quirks" in mind cause new series "root" folders are also created in a similar form -> `Series Name (Year)`
