### ISSUE TITLE
Order of metadata provider matters

### ISSUE THREAD

**Issue by SirLemyDanger** [MediaBrowser/Emby.AutoOrganize#31]
It seems to me that the order in which the meta data provider are configured for my library have a impact if metadata is found AT ALL.

I just tried to add tv show Power S01E07.  With a setting "TheTVDB" > "The Open Movie Database" > "TheMovieDb" I get an error like this in the log and Auto Organize is not organising the episode:

> 2019-06-06 17:32:44.740 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 4.1.1.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Unix 4.9.0.3
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///system/System.Private.CoreLib.dll
	Processor count: 8
	Program data path: /config
	Application directory: /system
	System.Exception: System.Exception: No provider metadata found for Power (2014) season 1 episode 7
	   at Emby.AutoOrganize.Core.FileOrganizationService.PerformOrganization(EpisodeFileOrganizationRequest request)
	Source: Emby.AutoOrganize
	TargetSite: Void MoveNext()

If I use "TheMovieDB" as the first meta data provider it works.

**Comment by LukePulverenti** [comment]
Hi, yes it should matter. Please attach the complete log file. thanks.

**Comment by SirLemyDanger** [comment]
sorry i don't have the complete log anymore

**Comment by LukePulverenti** [comment]
To answer the question, yes, your library fetcher order is used by auto-organize.
