### ISSUE TITLE
Season/Episode wont be preselected on manual sorting

### ISSUE THREAD

**Issue by daed-alus** [MediaBrowser/Emby.AutoOrganize#6]
season/episode dont get preselected in the corresponding input fields for manual sorting
broken since v1.2.0

**Comment by PoppyPop** [comment]
Hello, i was not able to reproduce with my setup.
Can you give me the file name that don't work ?

As you can see below, the season and episode number is assigned.

![image](https://user-images.githubusercontent.com/8221539/38644414-b1eec80c-3de0-11e8-9ce8-69a2252e5994.png)

**Comment by daed-alus** [comment]
something must have changes since i created the issue
its also working here again

**Comment by daed-alus** [comment]
problem is back and no matter what filename

![unbenannt](https://user-images.githubusercontent.com/16777083/39077445-1e474204-4502-11e8-8a76-8e9fc3191f60.PNG)

**Comment by PoppyPop** [comment]
I tried many time, but i was unable to reproduce. (i use the same filename).
From what i see, i have 2 primary causes : 
* The server does not recognize the name (i use Emby.Naming)
You can check the server log in debug for a line like `Extracted information from D:\....\blood-drive-s01e11-1080p.mkv. Series name blood-drive, Season 1, Episode 11`
If all is ok the server is not the culprit
* There is a javascript error,  Could you provide a javascript console log to help me track this bug ?

Also, could you provide server version and plugin version ?

**Comment by daed-alus** [comment]
server v3.3.1.24
plugin v1.2.3.0

season and episode number get extracted correctly by the server, if not already remembered patterns, that get sorted correctly, i think also wouldn't work

```
2018-04-25 23:30:32.241 Info App: Sorting file D:\...\steins-gate-s01e01-1080p.mkv
2018-04-25 23:30:32.303 Debug App: Extracted information from D:\...\steins-gate-s01e01-1080p.mkv. Series name steins-gate, Season 1, Episode 1
2018-04-25 23:30:32.361 Warn App: Unable to find series in library matching name steins-gate
```
![unbenannt2](https://user-images.githubusercontent.com/16777083/39274497-7163b9c0-48e2-11e8-8741-69e0296d5544.PNG)


sry don't know about javascript console logging

**Comment by daed-alus** [comment]
server3.4.0.0 & 3.4.0.1 beta comes with preselected mediatype 'movie' again and still empty season/episode#
